name: bank_sha
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.19.0
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
